[package]
name = "gdcode"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gdcode-lc", "gdcode-ui"]

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1

[profile.fastdev.package."*"]
opt-level = 3

[profile.fastdev]
inherits = "dev"
